name: ci-cd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node 12.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '12.x'

      - name: install @angular/cli && npm install && ng build
        run: |
          sudo npm install -g @angular/cli
          npm install
          ng build --prod
          pwd
          ls

      - uses: actions/upload-artifact@v2
        with:
          name: afk
          path: dist/afk-chrome-extension/


      - name: cd dist
        run: |
          cd dist/afk-chrome-extension
          pwd
